// GENERATED by `swift run brandgen`. Do not edit - add or import a mark
// and regenerate instead. Provenance per mark:
//   badge4k: tabler icons via Iconify (MIT)
//   badge8k: tabler icons via Iconify (MIT)
//   badgehd: tabler icons via Iconify (MIT)
//   badgesd: tabler icons via Iconify (MIT)
//   bluray: Wikimedia Commons (PD)
//   blurayglyph: Wikimedia Commons (PD), glyph split from the lockup
//   dolby: simple-icons (CC0)
//   dolbyatmos: Wikimedia Commons (PD)
//   dolbydigital: Wikimedia Commons (PD)
//   dolbydigitalplus: Wikimedia Commons (PD)
//   dolbytruehd: Wikimedia Commons (PD)
//   dolbyvision: Wikimedia Commons (PD)
//   dts: simple-icons (CC0)
//   dtshdma: Wikimedia Commons (PD)
//   dtswordmark: Wikimedia Commons (PD)
//   dvd: Wikimedia Commons (PD)
//   flac: Wikimedia Commons (PD, Xiph)
//   flages: Wikimedia Commons (PD), civil flag
//   hdr10: Wikimedia Commons (PD)
//   hdr10plus: Wikimedia Commons (PD)
//   imax: Wikimedia Commons (PD)
//   opus: Wikimedia Commons (PD, Xiph)
//   ultrahd: Wikimedia Commons (PD)
//   ultrahdbluray: Wikimedia Commons (PD)
//
// This enum belongs to the module that RENDERS these marks: resources
// cannot be tree-shaken, so brands never live in a shared base layer
// (Ink/Brand.swift states the rule). Marks are TEMPLATE images -
// shape, never color - so a consumer can tint them semantically while
// `color` stays the brand's own official hex.
import Ink
import SwiftUI

#if canImport(AppKit)
    import AppKit
#endif

public enum Mark: String, CaseIterable, Sendable, BrandMarkable {
    case badge4k = "badge4k"
    case badge8k = "badge8k"
    case badgehd = "badgehd"
    case badgesd = "badgesd"
    case bluray = "bluray"
    case blurayglyph = "blurayglyph"
    case dolby = "dolby"
    case dolbyatmos = "dolbyatmos"
    case dolbydigital = "dolbydigital"
    case dolbydigitalplus = "dolbydigitalplus"
    case dolbytruehd = "dolbytruehd"
    case dolbyvision = "dolbyvision"
    case dts = "dts"
    case dtshdma = "dtshdma"
    case dtswordmark = "dtswordmark"
    case dvd = "dvd"
    case flac = "flac"
    case flages = "flages"
    case hdr10 = "hdr10"
    case hdr10plus = "hdr10plus"
    case imax = "imax"
    case opus = "opus"
    case ultrahd = "ultrahd"
    case ultrahdbluray = "ultrahdbluray"

    /// The brand's own name, as its owner writes it.
    public var title: String {
        switch self {
        case .badge4k: "4K"
        case .badge8k: "8K"
        case .badgehd: "HD"
        case .badgesd: "SD"
        case .bluray: "Blu-ray Disc"
        case .blurayglyph: "Blu-ray Disc"
        case .dolby: "Dolby"
        case .dolbyatmos: "Dolby Atmos"
        case .dolbydigital: "Dolby Digital"
        case .dolbydigitalplus: "Dolby Digital Plus"
        case .dolbytruehd: "Dolby TrueHD"
        case .dolbyvision: "Dolby Vision"
        case .dts: "DTS"
        case .dtshdma: "DTS-HD Master Audio"
        case .dtswordmark: "DTS"
        case .dvd: "DVD"
        case .flac: "FLAC"
        case .flages: "Spain"
        case .hdr10: "HDR10"
        case .hdr10plus: "HDR10+"
        case .imax: "IMAX"
        case .opus: "Opus"
        case .ultrahd: "Ultra HD"
        case .ultrahdbluray: "Ultra HD Blu-ray"
        }
    }

    /// The official brand color.
    public var color: Color {
        switch self {
        case .badge4k: Color(red: 0.000, green: 0.000, blue: 0.000)  // #000000
        case .badge8k: Color(red: 0.000, green: 0.000, blue: 0.000)  // #000000
        case .badgehd: Color(red: 0.000, green: 0.000, blue: 0.000)  // #000000
        case .badgesd: Color(red: 0.000, green: 0.000, blue: 0.000)  // #000000
        case .bluray: Color(red: 0.000, green: 0.584, blue: 0.835)  // #0095D5
        case .blurayglyph: Color(red: 0.000, green: 0.584, blue: 0.835)  // #0095D5
        case .dolby: Color(red: 0.000, green: 0.000, blue: 0.000)  // #000000
        case .dolbyatmos: Color(red: 0.000, green: 0.000, blue: 0.000)  // #000000
        case .dolbydigital: Color(red: 0.000, green: 0.000, blue: 0.000)  // #000000
        case .dolbydigitalplus: Color(red: 0.000, green: 0.000, blue: 0.000)  // #000000
        case .dolbytruehd: Color(red: 0.000, green: 0.000, blue: 0.000)  // #000000
        case .dolbyvision: Color(red: 0.000, green: 0.000, blue: 0.000)  // #000000
        case .dts: Color(red: 0.976, green: 0.545, blue: 0.169)  // #F98B2B
        case .dtshdma: Color(red: 0.976, green: 0.545, blue: 0.169)  // #F98B2B
        case .dtswordmark: Color(red: 0.976, green: 0.545, blue: 0.169)  // #F98B2B
        case .dvd: Color(red: 0.000, green: 0.000, blue: 0.000)  // #000000
        case .flac: Color(red: 0.000, green: 0.000, blue: 0.000)  // #000000
        case .flages: Color(red: 0.776, green: 0.043, blue: 0.118)  // #C60B1E
        case .hdr10: Color(red: 0.000, green: 0.000, blue: 0.000)  // #000000
        case .hdr10plus: Color(red: 0.000, green: 0.000, blue: 0.000)  // #000000
        case .imax: Color(red: 0.000, green: 0.447, blue: 0.808)  // #0072CE
        case .opus: Color(red: 0.000, green: 0.000, blue: 0.000)  // #000000
        case .ultrahd: Color(red: 0.133, green: 0.118, blue: 0.122)  // #221E1F
        case .ultrahdbluray: Color(red: 0.000, green: 0.490, blue: 0.773)  // #007DC5
        }
    }

    /// Relative luminance of `color` (0 black … 1 white). A brand whose
    /// official color is near-black - GitHub's #181717, Metacritic's
    /// #000000 - vanishes on a dark surface, and the answer there is a
    /// shape-based treatment or an explicit tint, never a silent repaint
    /// of someone's logo.
    public var luminance: Double {
        switch self {
        case .badge4k: 0.000
        case .badge8k: 0.000
        case .badgehd: 0.000
        case .badgesd: 0.000
        case .bluray: 0.478
        case .blurayglyph: 0.478
        case .dolby: 0.000
        case .dolbyatmos: 0.000
        case .dolbydigital: 0.000
        case .dolbydigitalplus: 0.000
        case .dolbytruehd: 0.000
        case .dolbyvision: 0.000
        case .dts: 0.610
        case .dtshdma: 0.610
        case .dtswordmark: 0.610
        case .dvd: 0.000
        case .flac: 0.000
        case .flages: 0.204
        case .hdr10: 0.000
        case .hdr10plus: 0.000
        case .imax: 0.378
        case .opus: 0.000
        case .ultrahd: 0.121
        case .ultrahdbluray: 0.406
        }
    }

    /// Width over height of the artwork, from its viewBox. A symbol
    /// (≈1) sits in a disc; a lockup (≫1) runs inline with text.
    public var aspect: Double {
        switch self {
        case .badge4k: 1.000
        case .badge8k: 1.000
        case .badgehd: 1.000
        case .badgesd: 1.000
        case .bluray: 1.865
        case .blurayglyph: 2.273
        case .dolby: 1.000
        case .dolbyatmos: 3.911
        case .dolbydigital: 2.686
        case .dolbydigitalplus: 4.247
        case .dolbytruehd: 4.087
        case .dolbyvision: 2.674
        case .dts: 1.000
        case .dtshdma: 2.895
        case .dtswordmark: 2.550
        case .dvd: 2.272
        case .flac: 2.015
        case .flages: 1.500
        case .hdr10: 2.804
        case .hdr10plus: 2.804
        case .imax: 5.278
        case .opus: 1.761
        case .ultrahd: 5.750
        case .ultrahdbluray: 2.407
        }
    }

    /// Marks whose own colours ARE the mark (a flag, not a logo): rendered
    /// as authored, never template-tinted, whatever the caller passes.
    public var original: Bool {
        switch self {
        case .flages: true
        default: false
        }
    }

    #if canImport(AppKit)
        /// The artwork as AppKit sees it. Under Xcode the catalog is compiled
        /// and the named lookup answers; under `swift build` the catalog rides
        /// the bundle as a RAW folder (no actool), so the SVG is read straight
        /// from `Marks.xcassets/<slug>.imageset/<slug>.svg` - macOS renders SVG natively.
        public var nsImage: NSImage? {
            if let compiled = Bundle.module.image(forResource: rawValue) { return compiled }
            guard
                let url = Bundle.module.url(
                    forResource: rawValue, withExtension: "svg",
                    subdirectory: "Marks.xcassets/\(rawValue).imageset"),
                let loaded = NSImage(contentsOf: url)
            else { return nil }
            loaded.isTemplate = !original
            return loaded
        }
    #endif

    /// The mark itself; template-rendered unless `original`.
    public var image: Image {
        let mode: Image.TemplateRenderingMode = original ? .original : .template
        #if canImport(AppKit)
            if let ns = nsImage { return Image(nsImage: ns).renderingMode(mode) }
        #endif
        return Image(rawValue, bundle: .module).renderingMode(mode)
    }
}
