// GENERATED by `swift run brandgen`. Do not edit - add a brand and
// regenerate instead. Artwork + colors: simple-icons (CC0).
//
// Marks are TEMPLATE images: they carry shape, never color, so a
// consumer can tint them semantically (a rotten tomato going green)
// while `color` stays the brand's own official hex.
import SwiftUI

public enum Brand: String, CaseIterable, Sendable {
    case github = "github"
    case imdb = "imdb"
    case letterboxd = "letterboxd"
    case metacritic = "metacritic"
    case rottentomatoes = "rottentomatoes"
    case themoviedatabase = "themoviedatabase"
    case youtube = "youtube"

    /// The brand's own name, as its owner writes it.
    public var title: String {
        switch self {
        case .github: "GitHub"
        case .imdb: "IMDb"
        case .letterboxd: "Letterboxd"
        case .metacritic: "Metacritic"
        case .rottentomatoes: "Rotten Tomatoes"
        case .themoviedatabase: "The Movie Database"
        case .youtube: "YouTube"
        }
    }

    /// The official brand color.
    public var color: Color {
        switch self {
        case .github: Color(red: 0.094, green: 0.090, blue: 0.090)  // #181717
        case .imdb: Color(red: 0.961, green: 0.773, blue: 0.094)  // #F5C518
        case .letterboxd: Color(red: 0.125, green: 0.157, blue: 0.188)  // #202830
        case .metacritic: Color(red: 0.000, green: 0.000, blue: 0.000)  // #000000
        case .rottentomatoes: Color(red: 0.980, green: 0.196, blue: 0.039)  // #FA320A
        case .themoviedatabase: Color(red: 0.004, green: 0.706, blue: 0.894)  // #01B4E4
        case .youtube: Color(red: 1.000, green: 0.000, blue: 0.000)  // #FF0000
        }
    }

    /// Relative luminance of `color` (0 black … 1 white). A brand whose
    /// official color is near-black - GitHub's #181717, Metacritic's
    /// #000000 - vanishes on a dark surface, and the answer there is a
    /// shape-based treatment or an explicit tint, never a silent repaint
    /// of someone's logo.
    public var luminance: Double {
        switch self {
        case .github: 0.091
        case .imdb: 0.764
        case .letterboxd: 0.152
        case .metacritic: 0.000
        case .rottentomatoes: 0.351
        case .themoviedatabase: 0.570
        case .youtube: 0.213
        }
    }

    /// The mark itself, template-rendered (untinted).
    public var image: Image {
        Image(rawValue, bundle: .module).renderingMode(.template)
    }
}
